name: "Feature request"
title: "[feat] "
description: Suggest an improvement for NoteLoom
labels: ["type: feat"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Your suggestion
      description: Clearly describe the idea and what problem it would solve.
    validations:
      required: true
